### ISSUE TITLE
reset Gift/Redeemable after being redeemed

### ISSUE THREAD

**Issue by gravityblast** [status-im/keycard-redeem#9]

**Comment by bitgamma** [comment]
What do you mean? Why?

**Comment by gravityblast** [comment]
in the ERC20Bucket we reset the amount to 0, but we leave recipient and code.
Resetting them as well lower gas from 54k to 47k. 

For the NFT bucket would be the same. It would also allow to check if a gift exists without checking another contract. the same during redeem. 
To check old gifts we can check events/logs.

what do you think @bitgamma ?

**Comment by bitgamma** [comment]
for ERC20 if it lowers the gas then of course. For NFT bucket, I am not sure what is best. Because the way it is, even if you redeem you can still use it for authentication (which might be actually desired, no?). Maybe for NFTBucket we had a redeemed yes/no field? or simply reset the redeem code to mark redeemed stuff?

**Comment by gravityblast** [comment]
> which might be actually desired, no?
it would lower the gas here as well, and as we said for "partial redeem", I would just use it as a bucket and not for other feature like authentication. 
maybe if we add a redeem start time field then it's a general bucket and the creator can decide how to use authentication

**Comment by bitgamma** [comment]
why it lowers gas? not modifying the mapping costs more than modifying it?

**Comment by bitgamma** [comment]
ok, clear, let's do this
